Repository freifunkMUC/wg-access-server, pull requests merged in 2022-01, with the labels that each got.

#55 Upgrade Docker image to NodeJS 17
  Dockerfile
  website/package-lock.json
  website/package.json
  website/src/index.css
Labels: dependencies, javascript

#56 Allow disabling IPv4 NAT
  cmd/serve/main.go
  docs/2-configuration.md
  internal/config/config.go
  internal/network/network.go
Labels: enhancement, go

#57 Fix GitHub Pages deployment
  .github/workflows/build.yml
  .github/workflows/pages.yml
  .github/workflows/tests.yml
  mkdocs.yml
  requirements-docs.txt
Labels: bug, documentation

#64 Add features list to README, reorder introduction
  README.md
Labels: documentation

#80 Switch to our own pg-events fork
  go.mod
  go.sum
Labels: dependencies, go

#81 Always run npm build stage on host-native platform
  Dockerfile
Labels: docker

#84 Build and publish ppc64le and s390x images, limit parallel buildx jobs to 4
  .github/buildkitd.toml
  .github/workflows/build.yml
  .github/workflows/docker.yml
  .github/workflows/linting.yml
Labels: enhancement, docker

#85 Set node to a more fine-grained version
  Dockerfile
Labels: dependencies, docker
