Repository freifunkMUC/wg-access-server, pull requests merged in 2022-02, with the labels that each got.

#96 Create Helm update workflow
  .github/workflows/helm.yml
  .github/workflows/linting.yml
  publish.py
  scripts/requirements-update-helm.txt
  scripts/update-helm.py
Labels: enhancement

#95 Disable IPv6 by default and auto generate admin password in helm Chart
  deploy/helm/wg-access-server/README.md
  deploy/helm/wg-access-server/templates/NOTES.txt
  deploy/helm/wg-access-server/templates/_helpers.tpl
  deploy/helm/wg-access-server/templates/secret.yaml
  deploy/helm/wg-access-server/values.yaml
Labels: bug

#104 Add CAP_SYS_MODULE to Docker commands and docker-compose.yml
  README.md
  docker-compose.yml
  docs/deployment/1-docker.md
  docs/deployment/2-docker-compose.md
Labels: documentation, docker

#105 Don't add CAP_SYS_MODULE by default and other Docker documentation fixes
  README.md
  docker-compose.yml
  docs/deployment/1-docker.md
  docs/deployment/2-docker-compose.md
Labels: documentation
