Repository freifunkMUC/wg-access-server, pull requests merged in 2022-04, with the labels that each got.

#152 Document pgbouncer not working in 'Transaction pooling' mode
  docs/3-storage.md
Labels: documentation

#153 Allow comma as list separator for environment variables
  cmd/serve/main.go
  docs/2-configuration.md
Labels: enhancement, go

#132 Added: Mergeable configuration
  .github/mergeable.yml
  CHANGELOG.md
  README.md
Labels: documentation, enhancement

#155 Fix grpc recover and logging
  internal/services/api_router.go
  internal/services/health.go
  internal/services/middleware.go
  pkg/authnz/authconfig/oidc.go
Labels: bug, go

#156 Use WG kernel module implementation if available
  README.md
  cmd/serve/main.go
  docs/deployment/1-docker.md
  go.mod
  go.sum
Labels: enhancement, go

#137 Replace usage of deprecated github.com/golang/protobuf with google.golang.org/protobuf
  cmd/migrate/main.go
  codegen.sh
  go.mod
  go.sum
  internal/services/converters.go
  internal/services/device_service.go
  internal/services/server_service.go
  main.go
  pkg/authnz/authruntime/runtime.go
  proto/Dockerfile
  proto/proto/devices.pb.go
  proto/proto/devices_grpc.pb.go
  proto/proto/server.pb.go
  proto/proto/server_grpc.pb.go
Labels: enhancement, dependencies, go

#164 Remove Helm chart source files
  .github/workflows/codeql-analysis.yml
  .github/workflows/helm.yml
  .github/workflows/linting.yml
  README.md
  deploy/helm/wg-access-server/.helmignore
  deploy/helm/wg-access-server/Chart.yaml
  deploy/helm/wg-access-server/README.md
  deploy/helm/wg-access-server/templates/NOTES.txt
  deploy/helm/wg-access-server/templates/_helpers.tpl
  deploy/helm/wg-access-server/templates/configmap.yaml
  deploy/helm/wg-access-server/templates/deployment.yaml
  deploy/helm/wg-access-server/templates/ingress.yaml
  deploy/helm/wg-access-server/templates/pvc.yaml
  deploy/helm/wg-access-server/templates/secret.yaml
  deploy/helm/wg-access-server/templates/service.yaml
  deploy/helm/wg-access-server/values.yaml
  deploy/k8s/quickstart.yaml
  docs/deployment/3-kubernetes.md
  scripts/requirements-update-helm.txt
  scripts/update-helm.py
Labels: helm
