Repository freifunkMUC/wg-access-server, pull requests merged in 2022-03, with the labels that each got.

#106 Introduce authoritative-ish DNS server to serve domain names for client devices
  cmd/serve/main.go
  docs/2-configuration.md
  internal/config/config.go
  internal/devices/devices.go
  internal/devices/metadata.go
  internal/dnsproxy/auth.go
  internal/dnsproxy/proxy.go
  internal/dnsproxy/server.go
  internal/services/device_service.go
  internal/storage/gormwatcher.go
  internal/storage/inprocesswatcher.go
  internal/storage/pgwatcher.go
  internal/storage/sql.go
Labels: enhancement, go

#121 Report why oidc failure is happening
  pkg/authnz/authconfig/oidc.go
Labels: bug, go

#120 Rename module to github.com/freifunkMUC/wg-access-server
  cmd/migrate/main.go
  cmd/serve/main.go
  deploy/helm/wg-access-server/README.md
  go.mod
  internal/config/config.go
  internal/devices/devices.go
  internal/services/api_router.go
  internal/services/device_service.go
  internal/services/middleware.go
  internal/services/server_service.go
  main.go
  pkg/authnz/authconfig/authconfig.go
  pkg/authnz/authconfig/basic.go
  pkg/authnz/authconfig/gitlab.go
  pkg/authnz/authconfig/oidc.go
  pkg/authnz/authruntime/runtime.go
  pkg/authnz/authtemplates/login.go
  pkg/authnz/router.go
  proto/devices.proto
  proto/proto/devices.pb.go
  proto/proto/server.pb.go
  proto/server.proto
  website/src/sdk/devices_pb.ts
  website/src/sdk/server_pb.ts
Labels: enhancement, go

#126 Fix panic on nil LastHandshakeTime in metadata sync
  internal/devices/devices.go
  internal/devices/metadata.go
Labels: bug, go

#128 Move codegen steps from default into separate Dockerfile
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  proto/Dockerfile
  proto/proto/devices.pb.go
  proto/proto/server.pb.go
Labels: enhancement, docker

#129 helm: add option to configure wireguard.service.nodePort
  deploy/helm/wg-access-server/README.md
  deploy/helm/wg-access-server/templates/service.yaml
  deploy/helm/wg-access-server/values.yaml
Labels: enhancement, helm

#130 Update wg-embed to v0.6.0 and pg-events to v0.4.0
  cmd/serve/main.go
  go.mod
  go.sum
  internal/devices/devices.go
  internal/services/api_router.go
  internal/services/server_service.go
  internal/storage/pgwatcher.go
Labels: dependencies, go

#133 Return error if Helm update script fails
  scripts/update-helm.py
Labels: bug, github_actions

#123 When only a single auth is enabled, dont show auth selector
  cmd/serve/main.go
  docs/2-configuration.md
  pkg/authnz/authconfig/authconfig.go
  pkg/authnz/router.go
Labels: enhancement, go
