Repository freifunkMUC/wg-access-server, pull requests merged in 2023-07, with the labels that each got.

#402 Change welcome title to project name
  website/src/components/Navigation.tsx
  website/src/index.css
Labels: enhancement

#401 Adds a new client configuration item for maximum transmission unit 'MTU' (`clientconfig.mtu`).
  cmd/serve/main.go
  docs/2-configuration.md
  internal/config/config.go
  internal/services/server_service.go
  proto/proto/server.pb.go
  proto/server.proto
  website/src/components/AddDevice.tsx
  website/src/sdk/server_pb.ts
Labels: enhancement

#416 Improves logging
  .typos.toml
  cmd/serve/main.go
  internal/config/config.go
  internal/devices/devices.go
  internal/devices/inactive.go
  internal/devices/metadata.go
  internal/dnsproxy/server.go
  internal/network/network.go
  internal/services/device_service.go
  internal/services/website_router.go
  internal/storage/contracts.go
  internal/storage/contracts_test.go
  main.go
  pkg/authnz/authconfig/basic.go
  pkg/authnz/authconfig/oidc.go
  pkg/authnz/authsession/session.go
  pkg/authnz/router.go
Labels: enhancement

#420 Adds a device and user count the the all devices page.
  website/src/pages/admin/AllDevices.tsx
Labels: enhancement, javascript

#424 Gracefully terminates if configured OIDC auth server is not present on application start.
  cmd/serve/main.go
  pkg/authnz/authconfig/oidc.go
Labels: bug

#419 Adds version flag to software which is printed on startup.
  .github/workflows/build.yml
  .github/workflows/publish.yml
  Dockerfile
  buildinfo/buildinfo.go
  buildinfo/commit.txt
  buildinfo/get_commit.sh
  buildinfo/get_version.sh
  buildinfo/version.txt
  cmd/serve/main.go
  internal/services/server_service.go
  proto/buildinfo.proto
  proto/proto/buildinfo.pb.go
  proto/proto/server.pb.go
  proto/server.proto
  website/src/sdk/buildinfo_pb.ts
  website/src/sdk/server_pb.ts
Labels: enhancement

#429 add config to set the MTU on a interface
  cmd/serve/main.go
  docs/2-configuration.md
  go.mod
  go.sum
  internal/config/config.go
  internal/dnsproxy/server.go
  internal/services/server_service.go
  proto/proto/server.pb.go
  proto/server.proto
  website/src/sdk/server_pb.ts
Labels: enhancement
