Repository freifunkMUC/wg-access-server, pull requests merged in 2025-07, with the labels that each got.

#925 fix: Add return traffic rules when NAT is disabled
  internal/network/network.go
Labels: go

#926 feat: configurable HTTP and HTTPS listen addresses for the UI
  cmd/serve/main.go
  docs/2-configuration.md
  internal/config/config.go
Labels: documentation, go

#936 feat: add fields for optional Manual IP Assignment
  internal/devices/devices.go
  internal/services/device_service.go
  proto/devices.proto
  proto/proto/buildinfo.pb.go
  proto/proto/devices.pb.go
  proto/proto/devices_grpc.pb.go
  proto/proto/server.pb.go
  proto/proto/server_grpc.pb.go
  proto/proto/users.pb.go
  proto/proto/users_grpc.pb.go
  website/src/components/AddDevice.tsx
  website/src/components/AddDeviceSkeleton.tsx
  website/src/sdk/devices_pb.ts
Labels: enhancement, javascript, go
